#!/usr/bin/python3
if __name__ = "2-args":
import sys
s = len(sys.argv)
if s - 1 == 0:
     print("{} arguments.".format(s - 1))
elif s - 1  > 0:
    if s - 1 == 1:
        print("{} argument:".format(s - 1))
    elif (s - 1 > 1):
        print("{} arguments:".format(s - 1))

    for i in range(1, s):
        print("{}: {}".format(i, sys.argv[i]))
